### ISSUE TITLE
not working without recognizer.AddIntent

### ISSUE THREAD

**Issue by Unders0n** [MicrosoftDocs/azure-docs.ru-ru#180]
intent recognition was not working for me, i even created thread https://stackoverflow.com/questions/54764614/tutorial-speech-intent-recognition-not-working. But then i've tried to add recognizer.AddIntent wich i thought was part of preparing a model. faced up its not creating new intent its like mapping intent from app to application. 1)im i right? 2)without this lines its not working at all, so seems like its mandatory 3)why it done so and we can't just query all the model?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 2e2a2f45-6d55-0fef-6eec-0892577be3d9
* Version Independent ID: c776f260-6421-218d-758a-6b470200d720
* Content: [Руководство. Распознавание намерений из речи с помощью пакета SDK службы ](https://docs.microsoft.com/ru-ru/azure/cognitive-services/speech-service/how-to-recognize-intents-from-speech-csharp)
* Content Source: [articles/cognitive-services/Speech-Service/how-to-recognize-intents-from-speech-csharp.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/live/articles/cognitive-services/Speech-Service/how-to-recognize-intents-from-speech-csharp.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @wolfma61
* Microsoft Alias: **wolfma**

**Comment by CeciAc** [comment]
Hello, @Unders0n

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/28677

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
