### ISSUE TITLE
SnapshotsCollector

### ISSUE THREAD

**Issue by yahorsi** [MicrosoftDocs/azure-docs.ru-ru#405]
Article should mention how to configure SnapshotsCollector and include several varialns of the ApplicationInsights.config file. There are small samples but from the article it is hard to understand how the final document should look like. What is the real/final document structure.

PLS move to the English docs repo, sorry, for that.
Thanks

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: d924ee5e-1bf1-0d35-24e2-5b222e8e44c5
* Version Independent ID: f33fdb83-7734-b0b0-0ebd-25c0a5383c32
* Content: [Справочник по файлу ApplicationInsights.config в Azure](https://docs.microsoft.com/ru-ru/azure/azure-monitor/app/configuration-with-applicationinsights-config#feedback)
* Content Source: [articles/azure-monitor/app/configuration-with-applicationinsights-config.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/master/articles/azure-monitor/app/configuration-with-applicationinsights-config.md)
* Service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by srvbpigh** [comment]
Hello, @yahorsi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @yahorsi

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/35787

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
