### ISSUE TITLE
AzCopy v8 link is not work

### ISSUE THREAD

**Issue by SarapinIT** [MicrosoftDocs/azure-docs.ru-ru#593]
Redirect to v10 anyway

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 15911160-5ba2-fb0a-0b24-16b3857e20ce
* Version Independent ID: d925bc9f-f825-2f82-168c-6c30d716b9ce
* Content: [Копирование или перемещение данных в службу хранилища Azure с помощью AzCopy V10](https://docs.microsoft.com/ru-ru/azure/storage/common/storage-use-azcopy-v10?toc=%2Fazure%2Fstorage%2Ftables%2Ftoc.json)
* Content Source: [articles/storage/common/storage-use-azcopy-v10.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/master/articles/storage/common/storage-use-azcopy-v10.md)
* Service: **storage**
* Sub-service: **common**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by srvbpigh** [comment]
Hello, @SarapinIT
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @SarapinIT
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

Can you please specify which one is the broken link? I cannot repro it.
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @SarapinIT
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
