### ISSUE TITLE
C# version used

### ISSUE THREAD

**Issue by realsonic** [MicrosoftDocs/azure-docs.ru-ru#639]
Hi! There is a C# example on the page:
`tc.TrackEvent("CreatedAccount", new Dictionary<string,string> {"AccountType":account.Type}, null);`
Can you please clarify, what C# version is used? I can't run this code using the following Dictionary syntax: `new Dictionary<string,string> {"AccountType":account.Type}`.
Thanks.
---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: edce8383-4e3b-425b-5f01-02f54385b7a4
* Version Independent ID: bf51eb39-0bb9-262a-d4be-51b1bcb977f0
* Content: [Анализ использования с помощью Azure Application Insights - Azure Monitor](https://docs.microsoft.com/ru-ru/azure/azure-monitor/app/usage-overview#feedback)
* Content Source: [articles/azure-monitor/app/usage-overview.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/master/articles/azure-monitor/app/usage-overview.md)
* Service: **azure-monitor**
* Sub-service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by srvbpigh** [comment]
Hello, @realsonic
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @realsonic, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/56655. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
